[tool.poetry]
name = "snap"
version = "0.1.4"
description = ""
authors = ["micha <micha.vardy@tufin.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
